# Generated by Django 4.1.6 on 2023-02-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=2)),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('materia', models.CharField(blank=True, max_length=50)),
                ('cor', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=30)),
                ('turma', models.CharField(max_length=100)),
                ('tpi', models.CharField(max_length=20)),
                ('docente_teoria', models.CharField(max_length=100)),
                ('docente_pratica', models.CharField(max_length=100)),
                ('dia1', models.CharField(default='', max_length=30)),
                ('horario1', models.CharField(default='', max_length=30)),
                ('sala1', models.CharField(default='', max_length=30)),
                ('frequencia1', models.CharField(default='', max_length=30)),
                ('dia2', models.CharField(default='', max_length=30)),
                ('horario2', models.CharField(default='', max_length=30)),
                ('sala2', models.CharField(default='', max_length=30)),
                ('frequencia2', models.CharField(default='', max_length=30)),
                ('dia3', models.CharField(default='', max_length=30)),
                ('horario3', models.CharField(default='', max_length=30)),
                ('sala3', models.CharField(default='', max_length=30)),
                ('frequencia3', models.CharField(default='', max_length=30)),
                ('dia4', models.CharField(default='', max_length=30)),
                ('horario4', models.CharField(default='', max_length=30)),
                ('sala4', models.CharField(default='', max_length=30)),
                ('frequencia4', models.CharField(default='', max_length=30)),
                ('dia5', models.CharField(default='', max_length=30)),
                ('horario5', models.CharField(default='', max_length=30)),
                ('sala5', models.CharField(default='', max_length=30)),
                ('frequencia5', models.CharField(default='', max_length=30)),
                ('dia6', models.CharField(default='', max_length=30)),
                ('horario6', models.CharField(default='', max_length=30)),
                ('sala6', models.CharField(default='', max_length=30)),
                ('frequencia6', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TurmaPorRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=15)),
                ('codigo_turma', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='salas',
            name='horario1_fim',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salas',
            name='horario2_fim',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salas',
            name='horario3_fim',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salas',
            name='horario4_fim',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salas',
            name='horario5_fim',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salas',
            name='horario6_fim',
            field=models.CharField(default='', max_length=30),
        ),
    ]
