# Generated by Django 4.1.7 on 2023-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarioapp', '0002_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_principal_a', models.CharField(default='', max_length=250)),
                ('seg_veg_a', models.CharField(default='', max_length=250)),
                ('seg_guarnicao_a', models.CharField(default='', max_length=250)),
                ('seg_principal_j', models.CharField(default='', max_length=250)),
                ('seg_veg_j', models.CharField(default='', max_length=250)),
                ('seg_guarnicao_j', models.CharField(default='', max_length=250)),
                ('seg_saladas', models.CharField(default='', max_length=250)),
                ('seg_sobremesa', models.CharField(default='', max_length=250)),
                ('ter_principal_a', models.CharField(default='', max_length=250)),
                ('ter_veg_a', models.CharField(default='', max_length=250)),
                ('ter_guarnicao_a', models.CharField(default='', max_length=250)),
                ('ter_principal_j', models.CharField(default='', max_length=250)),
                ('ter_veg_j', models.CharField(default='', max_length=250)),
                ('ter_guarnicao_j', models.CharField(default='', max_length=250)),
                ('ter_saladas', models.CharField(default='', max_length=250)),
                ('ter_sobremesa', models.CharField(default='', max_length=250)),
                ('quar_principal_a', models.CharField(default='', max_length=250)),
                ('quar_veg_a', models.CharField(default='', max_length=250)),
                ('quar_guarnicao_a', models.CharField(default='', max_length=250)),
                ('quar_principal_j', models.CharField(default='', max_length=250)),
                ('quar_veg_j', models.CharField(default='', max_length=250)),
                ('quar_guarnicao_j', models.CharField(default='', max_length=250)),
                ('quar_saladas', models.CharField(default='', max_length=250)),
                ('quar_sobremesa', models.CharField(default='', max_length=250)),
                ('quinta_principal_a', models.CharField(default='', max_length=250)),
                ('quinta_veg_a', models.CharField(default='', max_length=250)),
                ('quinta_guarnicao_a', models.CharField(default='', max_length=250)),
                ('quinta_principal_j', models.CharField(default='', max_length=250)),
                ('quinta_veg_j', models.CharField(default='', max_length=250)),
                ('quinta_guarnicao_j', models.CharField(default='', max_length=250)),
                ('quinta_saladas', models.CharField(default='', max_length=250)),
                ('quinta_sobremesa', models.CharField(default='', max_length=250)),
                ('sexta_principal_a', models.CharField(default='', max_length=250)),
                ('sexta_veg_a', models.CharField(default='', max_length=250)),
                ('sexta_guarnicao_a', models.CharField(default='', max_length=250)),
                ('sexta_principal_j', models.CharField(default='', max_length=250)),
                ('sexta_veg_j', models.CharField(default='', max_length=250)),
                ('sexta_guarnicao_j', models.CharField(default='', max_length=250)),
                ('sexta_saladas', models.CharField(default='', max_length=250)),
                ('sexta_sobremesa', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
